graph LR
memo[mermaid로 플로우차트 그리기 docs 보기]
click memo "https://mermaid.js.org/syntax/flowchart.html"

A([시작]);B_1([끝1]);B_2([끝2]);C{판단 Y/N};D[처리1];E[처리2]
A-->C
C--YES-->D
C--NO-->E
D-->B_1
E-->B_2

node1([시작]);node2([끝]);node3[/입력/];node4[정보확인]
node1-->node3;node3-->node4;node4-->node2
