graph LR
A([시작]);B_1([끝1]);B_2([끝2]);C{판단 Y/N};D[처리1];E[처리2]
A-->C
C--YES-->D
C--NO-->E
D-->B_1
E-->B_2

graph LR
A([시작]);B_1([끝1]);B_2([끝2]);C{판단 Y/N};D[처리1];E[처리2]
A-->C
C--YES-->D
C--NO-->E
D-->B_1
E-->B_2
